# AWG Global Settings
driver_path:              /dev/spcm0    # the device file system handle : string 
external_clock_freq:      10000000      # Hz : int
channels:                 [0]           # list of channels : int[]
amp:                      [280]         # list of amp for each channel in mV : int[]

# Segment Settings
awg_num_segments:         256           # number of segments : int
sample_rate:              624e6         # sample rate : float 
wfm_mask:                 0x7fff        # waveform mask : Hex 
waveform_duration:        100e-6        # waveform duration : float
waveforms_per_segment:    32            # waveforms per segment : int 
null_segment_length:      62400         # null segment length : int
idle_segment_length:      62400         # idle segment length : int


# Trigger Settings
trigger_size:             2000          # number of Waveforms repeated for the synchronized trigger: int
vpp:                      280           # peak to peak voltage in mV : int


# EMCCD Trigger Settings
acq_timeout:              600           # acquisition timeout wait time for the EMCCD response in ms : int
async_trig_amp:           3             # trigger Amp in volts : int