waveform_duration: 10e-6                    # waveform duration : float

transition_type:   spline                    # Choose one of (TANH, spline, ERF)
  #  vmax: ...                               # For (TANH, ERF), provide V_max
static_type: sin                             # Choose one of (sin)

