---
num_trials_per_problem: 1
repetitions_per_trial: 1
allow_deficit: false
loss: true
seed: 0
problem_definition:
  experiment_params:
    roi_width: 1024
    roi_height: 1024
    roi_x_offset: 1
    roi_y_offset: 1
    detection_threshold: 800
    psf: psfs.bin
    coef_x: 21_traps.csv
    coef_y: default.csv
  problem_params:
    load_efficiency: 0.6
    Nt_x: 21
    Nt_y: 1
    num_target: 9
    array_geometry_type: rectangular lattice
    target_config: center compact
    algorithm: liblin_exact_1d_cpu_v2.so
  loss_atom_params:
    p_nu: 0.985
    p_alpha: 0.985
    t_lifetime: 60
  loss_env_params:
    t_alpha: 1.0e-05
    t_nu: 1.0e-05
    t_latency: 0.02
  geometry_params:
    trap_number:
    - 8
    - 16
    norms: 2.0e-06
    sampling_index: []
    z: 0
    shift_vector:
    - 0
    - 0
    - 0
    k1:
    - 1
    - 0
    - 0
    k2:
    - 0
    - 1
    - 0
    k3:
    - 0
    - 0
    - 1
    euler_angle:
    - - 0
      - 0
      - 0
    - rad
    coordinates: []
  uuid: c5380b4a-1bfa-4d56-be7f-772f87604cd8