# Configuration file for running the LLRS
problem_definition:
  experiment_params: 
    roi_width:    1024                            # int 
    roi_height:   1024                            # int 
    detection_threshold: 530                     # float
    psf:        psfs.bin                              # psf.bin,     see generate_psf
    coef_x:            21_traps.csv                       # default.csv 
    coef_y:         21_traps.csv                          # default.csv
  problem_params:
    Nt_x:         21                           # the x dimension of the trap array : int 
    Nt_y:         1                            # the y dimension of the trap array : int
    target_config_label:  centre_compact                    # type of the target configuration, choose one of (centre_compact, custom)
    target_config:                            # Array, this param is read only when custom is used  : int[] (binary array) 
    num_target:      1                          # this param is read only when centre_compact is used : int
    algorithm:      LINEAR-EXACT-1D                          # The algorithm to be used in the problem solving, choose one of (LINEAR-EXACT-1D, LINEAR-EXACT-V2-1D, REDREC-V2-2D, REDREC-CPU-V3-2D, ARO-2D, REDREC-GPU-V3-2D, BIRD-CPU-2D)
