# Configuration parameters for the runtime benchmarking problem
num_trials_per_problem: 1000      
repetitions_per_trial: 1

problem_definition:
  experiment_params: 
    roi_width:   1024                           # int 
    roi_height:  16                             # int 
    detection_threshold: 800                    # float
    psf:     64.bin                             # psfs.bin,     see generate_psf
    coef_x:    21_traps.csv                     # default.csv 
    coef_y:    21_traps.csv                     # default.csv
  problem_params:
    Nt_x:      1                                # the x dimension of the trap array : int 
    Nt_y:      64                               # the y dimension of the trap array : int
    target_config_label:  centre_compact        # type of the target configuration, choose one of (centre_compact, custom)
    array_geometry_type:  rectangular lattice   # type of the array geometry, choose one of (rectangular lattice)
    load_efficiency:    0.6                     # the load efficiency of the trap array : float
    target_config:      center compact          # Array, this param is read only when custom is used  : int[] (binary array) 
    num_target:         32                      # this param is read only when centre_compact is used : int
    algorithm:          LINEAR-EXACT-V2-1D      # The algorithm to be used in the problem solving, choose one of {LINEAR-EXACT-1D, LINEAR-EXACT-V2-1D, REDREC-V2-2D, REDREC-CPU-V3-2D, ARO-2D, REDREC-GPU-V3-2D, BIRD-CPU-2D}

# configuration for the pre-solved problems
  loss_atom_params:
    p_nu: 0.985
    p_alpha: 0.985
    t_lifetime: 60
  loss_env_params:
    t_alpha: 1.0e-05
    t_nu: 1.0e-05
    t_latency: 0.02

enable_problem_range: False                   # set to false to only use base problem def   
