num_trials_per_problem: 1      
repetitions_per_trial: 1
allow_deficit: false
loss: true
seed: 0
  problem_params:
    load_efficiency: 0.6
    Nt_x: 21
    Nt_y: 1
    num_target: 9
    array_geometry_type: rectangular lattice
    target_config: center compact
    algorithm: liblin_exact_1d_cpu_v2.so
  loss_atom_params:
    p_nu: 0.985
    p_alpha: 0.985
    t_lifetime: 60
  loss_env_params:
    t_alpha: 1.0e-05
    t_nu: 1.0e-05
    t_latency: 0.02
  geometry_params:
    trap_number:
    - 8
    - 16
    norms: 2.0e-06
    sampling_index: []
    z: 0
    shift_vector:
    - 0
    - 0
    - 0
    k1:
    - 1
    - 0
    - 0
    k2:
    - 0
    - 1
    - 0
    k3:
    - 0
    - 0
    - 1
    euler_angle:
    - - 0
      - 0
      - 0
    - rad
    coordinates: []
  uuid: c5380b4a-1bfa-4d56-be7f-772f87604cd8
problem_definition:
  experiment_params: 
    roi_width:                                # int 
    roi_height:                               # int 
    detection_threshold:                      # float
    psf:                                      # psf.bin,     see generate_psf
    coef_x:                                   # default.csv 
    coef_y:                                   # default.csv
  problem_params:
    Nt_x:                                     # the x dimension of the trap array : int 
    Nt_y:                                     # the y dimension of the trap array : int
    target_config_label:                      # type of the target configuration, choose one of {centre_compact, custom}
    target_config:                            # Array, this param is read only when custom is used  : int[] (binary array) 
    num_target:                               # this param is read only when centre_compact is used : int
    algorithm:                                # The algorithm to be used in the problem solving, choose one of {LINEAR-EXACT-1D, LINEAR-EXACT-V2-1D, REDREC-V2-2D, REDREC-CPU-V3-2D, ARO-2D, REDREC-GPU-V3-2D, BIRD-CPU-2D}
