problem_definition:
  experiment_params: 
    roi_width:                                # int 
    roi_height:                               # int 
    detection_threshold:                      # float
    psf:                                      # psf.bin,     see generate_psf
    coef_x:                                   # default.csv 
    coef_y:                                   # default.csv
  problem_params:
    Nt_x:                                     # the x dimension of the trap array : int 
    Nt_y:                                     # the y dimension of the trap array : int
    target_config_label:                      # type of the target configuration, choose one of {centre_compact, custom}
    target_config:                            # Array, this param is read only when custom is used  : int[] (binary array) 
    num_target:                               # this param is read only when centre_compact is used : int
    algorithm:                                # The algorithm to be used in the problem solving, choose one of {LINEAR-EXACT-1D, LINEAR-EXACT-V2-1D, REDREC-V2-2D, REDREC-CPU-V3-2D, ARO-2D, REDREC-GPU-V3-2D, BIRD-CPU-2D}
