name: AWG Driver Package
on:
  repository_dispatch:
    types: awg-release
jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Release Asset
        env:
          GH_TOKEN: ${{ secrets.instruments_token }}  
        run: gh release download awg -R TQT-RAAQS/Instruments -A zip
      - name: Unarchive
        run: unzip Instruments-awg.zip 
      - name: Move AWG
        run: mv Instruments-awg/awg modules/awg
      - name: Clean up
        run: rm -rf Instruments-awg*
      - name: Commit Release Asset
        run: |
          git config --global user.name "TQTRAAQS"
          git config --global user.email "tqtraaqs@gmail.com"
          git add -f modules/awg
          git commit -m "Add release asset from Instruments/awg"
          git push 

      
