name: AWG Driver Package
on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: download 
        uses: robinraju/release-downloader@v1.9
        with: 
          repository: "TQT-RAAQS/Instruments"
          tag: "awg"
          tarBall: false
          zipBall: true
          extract: true
          token: ${{ secrets.instruments_token }}
      - name: list
        run: ls

      
