name: FGC Driver Package
on:
  repository_dispatch:
    types: fgc-release
jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Release Asset
        env:
          GH_TOKEN: ${{ secrets.instruments_token }}  
        run: gh release download fgc -R TQT-RAAQS/Instruments -A zip
      - name: Unarchive
        run: unzip Instruments-fgc.zip 
      - name: Move FGC
        run: mv Instruments-fgc/fgc modules/ -f
      - name: Clean up
        run: rm -rf Instruments-fgc*
      - name: Commit Release Asset
        run: |
          git config --global user.name "TQTRAAQS"
          git config --global user.email "tqtraaqs@gmail.com"
          git add -f modules/fgc
          git commit -m "Add release asset from Instruments/fgc"
          git push 

      
